from __future__ import annotations

from pathlib import Path

RUNS = Path("runs")
SHARED_ASSETS = RUNS / "00_shared_assets"

DECAY_MODEL = RUNS / "01_exponential_decay"
DECAY_MCMC_HMC_ROOT = DECAY_MODEL / "01_mcmc_hmc_reference"
DECAY_NPE_STAGE1_ROOT = DECAY_MODEL / "02_npe_stage1_local_summary"
DECAY_NPE_FLOW_ROOT = DECAY_MODEL / "03_npe_flow_search"
DECAY_SNPE_SBI_ROOT = DECAY_MODEL / "04_snpe_sbi"
DECAY_ABC_ROOT = DECAY_MODEL / "05_abc_faithfulness"
DECAY_ORACLE_ROOT = DECAY_MODEL / "06_oracle_target_checks"

DECAY_RUN = DECAY_MCMC_HMC_ROOT / "00_root_decay_sampler_results"
DECAY_RESULTS = DECAY_RUN / "results"
DECAY_FIGURES = DECAY_RUN / "figures"
MCMC_DEVICE_RESULTS = DECAY_MCMC_HMC_ROOT / "03_mcmc_device_benchmarks" / "results"

MCMC_DECAY_SAMPLES = DECAY_RESULTS / "mcmc_decay_samples.npz"
HMC_DECAY_SAMPLES = DECAY_RESULTS / "hmc_decay_samples.npz"
MCMC_DECAY_SUMMARY = DECAY_RESULTS / "mcmc_decay_summary.json"
HMC_DECAY_SUMMARY = DECAY_RESULTS / "hmc_decay_summary.json"
SAMPLER_COMPARISON_SUMMARY = DECAY_RESULTS / "sampler_comparison_summary.json"
MCMC_HMC_NPE_CORNER_OVERLAY = DECAY_FIGURES / "mcmc_hmc_npe_corner_overlay.png"
DECAY_THETA_EXAMPLES = SHARED_ASSETS / "01_exponential_decay_theta_examples.svg"
MCMC_DEVICE_BENCHMARK = MCMC_DEVICE_RESULTS / "mcmc_device_benchmark.json"

NPE_FOCUSED_RUN = DECAY_NPE_STAGE1_ROOT / "01_npe_focused"
NPE_FOCUSED_RESULTS = NPE_FOCUSED_RUN / "results"
NPE_FOCUSED_FIGURES = NPE_FOCUSED_RUN / "figures"
NPE_LOCAL_REGION_RUN = DECAY_NPE_STAGE1_ROOT / "00_npe_local_region"
NPE_LOCAL_REGION_RESULTS = NPE_LOCAL_REGION_RUN / "results"
NPE_LOCAL_REGION_FIGURES = NPE_LOCAL_REGION_RUN / "figures"
NPE_LOCAL_REGION_Q0005_MDN_20K_RESULTS = (
    DECAY_NPE_STAGE1_ROOT / "05_npe_local_region_q0005_mdn_20k" / "results"
)
NPE_MULTI_X_RUN = DECAY_NPE_STAGE1_ROOT / "08_npe_multi_x"
NPE_MULTI_X_RESULTS = NPE_MULTI_X_RUN / "results"
NPE_MULTI_X_FIGURES = NPE_MULTI_X_RUN / "figures"
NPE_STAGE1_RUN = DECAY_NPE_STAGE1_ROOT / "11_npe_stage1"
NPE_STAGE1_RESULTS = NPE_STAGE1_RUN / "results"
NPE_STAGE1_FIGURES = NPE_STAGE1_RUN / "figures"
NPE_STAGE1_SCALED_RESULTS = DECAY_NPE_STAGE1_ROOT / "12_npe_stage1_scaled" / "results"
NPE_SUMMARY_CONTEXT_RUN = DECAY_NPE_STAGE1_ROOT / "00_npe_summary_context"
NPE_SUMMARY_CONTEXT_RESULTS = NPE_SUMMARY_CONTEXT_RUN / "results"
NPE_SUMMARY_CONTEXT_FIGURES = NPE_SUMMARY_CONTEXT_RUN / "figures"

NPE_FLOW_DECAY_RUN = DECAY_NPE_FLOW_ROOT / "00_npe_flow_decay"
NPE_FLOW_DECAY_RESULTS = NPE_FLOW_DECAY_RUN / "results"
NPE_FLOW_DECAY_FIGURES = NPE_FLOW_DECAY_RUN / "figures"
NPE_FLOW_TARGET_PASS_RESULTS = (
    DECAY_NPE_FLOW_ROOT / "11_npe_flow_local_q0005_linear_150k_t8_seed20260706" / "results"
)

SBI_ALTERNATE_RUN = DECAY_SNPE_SBI_ROOT / "00_sbi_alternate"
SBI_ALTERNATE_RESULTS = SBI_ALTERNATE_RUN / "results"
SBI_ALTERNATE_FIGURES = SBI_ALTERNATE_RUN / "figures"
SNPE_SBI_RUN = DECAY_SNPE_SBI_ROOT / "00_snpe_sbi"
SNPE_SBI_RESULTS = SNPE_SBI_RUN / "results"
SNPE_SBI_FIGURES = SNPE_SBI_RUN / "figures"
SNPE_SBI_SUMMARY_RUN = DECAY_SNPE_SBI_ROOT / "00_snpe_sbi_summary"
SNPE_SBI_SUMMARY_RESULTS = SNPE_SBI_SUMMARY_RUN / "results"
SNPE_SBI_SUMMARY_FIGURES = SNPE_SBI_SUMMARY_RUN / "figures"
SNPE_SEQUENTIAL_RUN = DECAY_SNPE_SBI_ROOT / "00_snpe_sequential"
SNPE_SEQUENTIAL_RESULTS = SNPE_SEQUENTIAL_RUN / "results"
SNPE_SEQUENTIAL_FIGURES = SNPE_SEQUENTIAL_RUN / "figures"
SNPE_SEQUENTIAL_GAUSSIANS_RESULTS = DECAY_SNPE_SBI_ROOT / "06_snpe_sequential_gaussians_r4_n25k" / "results"
SNPE_SEQUENTIAL_MDN_RESULTS = DECAY_SNPE_SBI_ROOT / "07_snpe_sequential_mdn_r4_n25k" / "results"

ABC_FAITHFULNESS_RUN = DECAY_ABC_ROOT / "01_abc_faithfulness"
ABC_FAITHFULNESS_RESULTS = ABC_FAITHFULNESS_RUN / "results"
ABC_FAITHFULNESS_FIGURES = ABC_FAITHFULNESS_RUN / "figures"
FAITHFULNESS_TARGET_RUN = DECAY_ORACLE_ROOT / "01_faithfulness_target_check"
FAITHFULNESS_TARGET_RESULTS = FAITHFULNESS_TARGET_RUN / "results"
FAITHFULNESS_TARGET_FIGURES = FAITHFULNESS_TARGET_RUN / "figures"
ORACLE_POSTERIOR_RUN = DECAY_ORACLE_ROOT / "02_oracle_posterior_fit"
ORACLE_POSTERIOR_RESULTS = ORACLE_POSTERIOR_RUN / "results"
ORACLE_POSTERIOR_FIGURES = ORACLE_POSTERIOR_RUN / "figures"

STRESS_SIGN_NPE_ROOT = RUNS / "02_stress_sign" / "01_npe_flow"
STRESS_BANANA_NPE_ROOT = RUNS / "03_stress_banana" / "01_npe_flow"
STRESS_LABEL_SWITCH_NPE_ROOT = RUNS / "04_stress_label_switch" / "01_npe_flow"
STRESS_LINEAR6_NPE_ROOT = RUNS / "05_stress_linear6" / "01_npe_flow"
TWO_EXP_NPE_ROOT = RUNS / "06_two_exponential" / "01_npe_flow"
TWO_EXP_SBI_ROOT = RUNS / "06_two_exponential" / "02_sbi"

STRESS_RUN_ROOT = STRESS_SIGN_NPE_ROOT / "00_npe_flow_stress_tests"
STRESS_RESULTS_ROOT = STRESS_RUN_ROOT
STRESS_FIGURES_ROOT = STRESS_RUN_ROOT
TWO_EXP_RIDGECOORDS_RESULTS = (
    TWO_EXP_NPE_ROOT / "16_npe_flow_stress_tests_two_exp_ordered_ridgecoords" / "results"
)
SBI_TWO_EXP_ORDERED_RUN = TWO_EXP_SBI_ROOT / "00_sbi_two_exp_ordered"
SBI_TWO_EXP_ORDERED_RESULTS = SBI_TWO_EXP_ORDERED_RUN / "results"
SBI_TWO_EXP_ORDERED_FIGURES = SBI_TWO_EXP_ORDERED_RUN / "figures"
